name: flashride_app
description: FlashRide – mapa + autocomplete sin conflictos
publish_to: "none"
version: 1.1.4+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Mapas
  google_maps_flutter: ^2.13.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # HTTP / ubicación / storage
  http: ^1.2.2
  geolocator: ^11.1.0
  shared_preferences: ^2.2.2

  # UI/otros
  cupertino_icons: ^1.0.2
  logging: ^1.1.0
  flutter_polyline_points: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_taxi_appicon.png"
